# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle
 
on:
# Events : 
# Everytime someone will pushes the the master brach or pull from the master branch 
# (if we want to merge something to the master branch), this will triggers the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
#Jobs = combinations of actions 

  build:

    runs-on: ${{matrix.os}}
    strategy: 
     matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]      

    steps:
    - uses: actions/checkout@v3 # Checks out the repository or the code first
    
    #Prepare Java environment that our job can run in 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
        
    #To help mitigate the runtime of the build in a GitHub-runner
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 
        
    - name: Build project with Maven
      run: mvn -B package --file pom.xml


 
