# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle
 
on:
# Events : 
# Everytime someone will pushes the the master brach or pull from the master branch 
# (if we want to merge something to the master branch), this will triggers the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
#Jobs = combinations of actions 

  build:

    runs-on: ${{matrix.os}}
    strategy: 
     matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]
      
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3 # Checks out the repository or the code first
    
    #Prepare Java environment that our job can run in 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11 '
        distribution: 'temurin' 
        
    - name: Build project with Maven
      run: mvn -B package --file pom.xml

  publish-job:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - run: mvn -B package --file pom.xml -DskipTests
        - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
